test/src/objects/Candidate__c.object
<CustomObject>
    <description>Represent an applicant who might apply for one or more positions.</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <externalId>true</externalId>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

test/src/classes/wraperclass.cls
public class wraperclass{
    public boolean passbooleanvalue;
    public list<Candidate__c> passallcan;
    public list<subclass> alldatatoshow{get;set;}
    public wraperclass(){
        alldatatoshow = new list<subclass>();
        passbooleanvalue = false;
        passallcan = [select id,name, First_Name__c from Candidate__c limit 1];
        for(integer i=0; i<passallcan.size(); i++){
            subclass singlerecord = new subclass(passbooleanvalue, passallcan[i]);
            alldatatoshow.add(singlerecord );
            }
        }
     public void deleterecords(){
         for(integer i=0;i<alldatatoshow.size();i++){
             if(alldatatoshow[i].trueorfalse == true){
                 system.debug('number of cadidates selected to delete=========>'+i);
                 //delete alldatatoshow[i].allcandidates;
                 }
             }
         }
     }