test/src/objects/Candidate__c.object
<CustomObject>
    <description>Represent an applicant who might apply for one or more positions.</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <externalId>true</externalId>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

test/src/classes/splitstring.cls
public with sharing class splitstring {

    public String allsearch { get; set; }
    
    public list<Candidate__c> allcan { get; set; }

    public void checkdatainaccount() {
    
        list<string> allstrs = allsearch.split(',');
        
        system.debug('all data size==========>'+allstrs.size());
        
        allcan = [select id, name, First_Name__c from Candidate__c where name=:allstrs];
        
        system.debug('number of candidates========>'+allcan.size());
               
    }


    }