test/src/objects/Candidate__c.object
<CustomObject>
    <description>Represent an applicant who might apply for one or more positions.</description>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

test/src/objects/Job_Application__c.object
<CustomObject>
    <description>Represents a candidate&apos;s apllication to a position.</description>
    <fields>
        <fullName>Candidate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{00000}</displayFormat>
        <label>Job Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

test/src/objects/Position__c.object
<CustomObject>
    <description>This object stores information about open job positions at our company.</description>
    <label>Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

test/src/classes/appinfo1.cls
public with sharing class appinfo1 {
    public appinfo1(ApexPages.StandardController controller) {
        system.debug('id in constructot=========>'+canrec);
        jobapp=[select id, Candidate__c, Position__c,Position__r.name from Job_Application__c where Candidate__c=:canrec];

    }



public list<Job_Application__c> jobapp{get; set;}
id canrec = apexpages.currentpage().getparameters().get('id');

}