test/src/objects/Invoice_Statement1__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Invoice Statement1</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Statement1 Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Statement1s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

test/src/objects/Line_Item1__c.object
<CustomObject>
    <fields>
        <fullName>Invoice_Statement1__c</fullName>
        <label>Invoice Statement1</label>
        <referenceTo>Invoice_Statement1__c</referenceTo>
        <relationshipLabel>Line Item1s</relationshipLabel>
        <relationshipName>Line_Item1s</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Merchandise1__c</fullName>
        <label>Merchandise1</label>
        <referenceTo>Merchandise1__c</referenceTo>
        <relationshipLabel>Line Item1s</relationshipLabel>
        <relationshipName>Line_Item1s</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Units_Sold__c</fullName>
        <label>Units Sold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Line Item1</label>
    <nameField>
        <label>Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Item1s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

test/src/objects/Merchandise1__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Inventory__c</fullName>
        <label>Total Inventory</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Merchandise1</label>
    <nameField>
        <label>Merchandise1 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise1</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

test/src/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
public static Invoice_Statement1__c createOneInvoiceStatement(
Boolean withLineItem) {
// Create one invoice statement
Invoice_Statement1__c testInvoice = createInvoiceStatement();
if (withLineItem == true) {
// Create a merchandise item
Merchandise1__c m = createMerchandiseItem('Orange juice');
// Create one line item and associate it with the invoice statement.
AddLineItem(testInvoice, m);
}
return testInvoice;
}
// Helper methods
    private static Merchandise1__c createMerchandiseItem(String merchName) {
Merchandise1__c m = new Merchandise1__c(
Name=merchName,
Description__c='Fresh juice',
Price__c=2,
Total_Inventory__c=1000);
insert m;
return m;
}
private static Invoice_Statement1__c createInvoiceStatement() {
Invoice_Statement1__c inv = new Invoice_Statement1__c(
Description__c='Test Invoice');
insert inv;
return inv;
}
private static Line_Item1__c AddLineItem(Invoice_Statement1__c inv,
Merchandise1__c m) {
Line_Item1__c lineItem = new Line_Item1__c(
Invoice_Statement1__c = inv.Id,
Merchandise1__c = m.Id,
Unit_Price__c = m.Price__c,
Units_Sold__c = (Double)(10*Math.random()+1));
insert lineItem;
return lineItem;
}
}